/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:a8d4e514-b9e9-4de4-8ecd-1368e9004f05",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_RBVqhz5l5",
    "aws_user_pools_web_client_id": "533jba62i4a86v47jlu1c4gihs",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://3zo32l7lcvhetklxoz5zlxb5pi.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "predictions": {
        "convert": {
            "transcription": {
                "region": "eu-central-1",
                "proxy": false,
                "defaults": {
                    "language": "en-US"
                }
            },
            "speechGenerator": {
                "region": "eu-central-1",
                "proxy": false,
                "defaults": {
                    "VoiceId": "Kendra",
                    "LanguageCode": "en-US"
                }
            }
        }
    }
};


export default awsmobile;
